### ISSUE TITLE
Possible frontend features

### ISSUE THREAD

**Issue by aboutaaron** [california-civic-data-coalition/django-calaccess-campaign-browser#123]
## General
- [x] Consistent breadcrumbs
- [ ] Create new templates for pages
  - [x] Parties
  - [ ] Top PACs
  - [ ] Elections
- [ ] Open source any JS or Python we write into the general organization page

## Latest Page
- [ ] timestamp of latest data (when was this last updated?)
- [ ] Highlight top 10s

## Filer Detail Page
- [ ] Candidate information from Sunlight or alt source?
- [ ] Remove candidate type from candidate committee table (double check if that makes sense)
- [ ] Timeline / Histogram for committees in page?
- [ ] Add years active, e.g., this committee operated from 2006-2009
- [x] Add totals

## Committee Detail Page
- [ ] Add crossfilter code to page
- [x] Link to original filer if applicable
- [x] Histogram of filings on Committee page
- [x] Better visual distinction between contributions and expenditures
- [ ] Search by contributor or expenditure name (via #108)
- [ ] Filter by type fields (via #108)
- [ ] Filter by cycle or year or filing period or whatever (via #108)
- [ ] Badges of labels for Politcal parties
- [ ] Add candidate information from Sunlight or other source when applicable?
- [x] Biggest donor (frequency?)

**Comment by kavyasukumar** [comment]
Added histogram of contributions and expenditures

**Comment by livlab** [comment]
Parties template has been created, just needs some data now. :)

**Comment by aboutaaron** [comment]
Awesome! Can yall add a link to it on the app navigation?

—

**Comment by palewire** [comment]
I'm going to move many of these into new, smaller tickets, potentially for use at a future event.
